version: '3'

networks:
  sofertas:
    ipam:
      config:
        - subnet: 172.23.0.0/24
services:
  mongodb:
    image: mysql:latest
    restart: always
    networks:
      sofertas:
        ipv4_address: 172.23.0.2
    volumes:
      - mongodb_data:/home/blackraider/Proyectos/node/SOfertas/db
  app:
    image: blackraider/sofertas
    depends_on:
      - mongodb
    networks:
      wordpress:
        ipv4_address: 172.23.0.3
    ports:
      - 8080:80
    restart: always
    environment:
      MONGODB_HOST: mongodb
volumes:
  mongodb_data:
    driver: local
